### ISSUE TITLE
Not clear on how to use 'merge-assignment-solutions'

### ISSUE THREAD

**Issue by reidka** [gitomator/gitomator-classroom#4]
I'm getting an "Invalid GitHub hosting configuration" error.  I think I don't quite understand whether I have the right access token, or whether I am missing some other configuration detail.  The argument to merge-assignment solutions is a yml file that looks like the one passed into make-repos.

Is this a "personal access token"? https://github.com/settings/tokens/new

Error message (with some anonymization):

```
D, [2016-09-24T22:19:33.511349 #16059] DEBUG -- : Merging solutions from 1 handout(s).
I, [2016-09-24T22:19:33.511442 #16059]  INFO -- : lab1-student (1 out of 1)
E, [2016-09-24T22:19:33.514493 #16059] ERROR -- : Invalid GitHub hosting configuration - {"provider"=>"github", "access-token"=>"####", "organization"=>"ORG_NAME"} (lab1-student).

/usr/local/lib/ruby/gems/2.3.0/bundler/gems/gitomator-github-b91743974300/lib/gitomator/github.rb:22:in `github_client_from_config'
        /usr/local/lib/ruby/gems/2.3.0/bundler/gems/gitomator-github-b91743974300/lib/gitomator/github/tagging_provider.rb:17:in `from_config'
        /Users/reid/teaching/csc309/gitomator-classroom/lib/gitomator/classroom/context.rb:34:in `create_github_tagging_service'
        /usr/local/lib/ruby/gems/2.3.0/bundler/gems/gitomator-882809ebadfa/lib/gitomator/context.rb:23:in `block (2 levels) in initialize'
        /usr/local/lib/ruby/gems/2.3.0/bundler/gems/gitomator-882809ebadfa/lib/gitomator/context.rb:40:in `block in register_service'
        /usr/local/lib/ruby/gems/2.3.0/bundler/gems/gitomator-882809ebadfa/lib/gitomator/task.rb:39:in `tagging'
        bin/workflow/merge-assignment-solutions:69:in `has_merged_solution?'
        bin/workflow/merge-assignment-solutions:51:in `merge_solution'
        bin/workflow/merge-assignment-solutions:40:in `block in run'
        bin/workflow/merge-assignment-solutions:37:in `each'
        bin/workflow/merge-assignment-solutions:37:in `each_with_index'
        bin/workflow/merge-assignment-solutions:37:in `run'
        /Users/reid/teaching/csc309/gitomator-classroom/lib/gitomator/classroom/script_util.rb:50:in `run_task'
        bin/workflow/merge-assignment-solutions:87:in `<main>'
D, [2016-09-24T22:19:33.514668 #16059] DEBUG -- : Done.
```

My .gitomator file:

```
hosting:
  provider: github
  username: USERID
  password: PASSWORD
  organization: ORG_NAME

tagging:
  provider: github
  access-token: ACCESS_TOKEN
  organization: ORG_NAME
```

**Comment by joeyfreund** [comment]
In your `~/.gitomator`, try changing `access-token` to `access_token`.  
Does it fix the issue?

**Comment by reidka** [comment]
bleh.  Shouldn't trying to do this late at night.  Thanks for spotting the typo
